# -*- coding: utf-8 -*-
"""TITANIC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZa2Hon84OSPDxSYAQVAuD-Oebxfw7uT
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df=pd.read_csv("train.csv")

df.head()

df.isnull().sum()

df=df.drop(
    columns=[
        "PassengerId",
        "Name",
        "Ticket",
        "Cabin",
        "Fare"
    ]
)

df["Age"]=df["Age"].fillna(df["Age"].median())
df["Embarked"]=df["Embarked"].fillna(df["Embarked"].mode()[0])

le=LabelEncoder()
df["Sex"]=le.fit_transform(df["Sex"])

df = pd.get_dummies(
    df,
    columns=["Embarked"],
    drop_first=True
)

X=df.drop("Survived",axis=1)
Y=df["Survived"]

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,
Y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,Y_train)

prediction=model.predict(X_test)
print(prediction)

print(model.score(X_test,Y_test))

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(confusion_matrix(Y_test,prediction))
print(classification_report(Y_test,prediction,target_names=["Died","Survived"]))

